applied PackageJanitor

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -2,6 +2,9 @@ name: Tests
 
 on:
   push:
+    branches:
+      - "master"
+      - "*-ci"
   pull_request:
   schedule:
     - cron: "0 0 * * *"
@@ -22,8 +25,24 @@ jobs:
       - run: |
           export HOME="/home/gap"
           cd /home/gap/.gap/pkg/
-          git clone --depth 1 https://github.com/gap-packages/AutoDoc
+          sudo apt update
+          sudo apt dist-upgrade -y
+          sudo apt install -y texlive-latex-extra texlive-fonts-extra
+          git clone --depth 1 https://github.com/gap-packages/AutoDoc.git
           git clone --depth 1 https://github.com/homalg-project/homalg_project.git
-          cd LoopIntegrals
-          TERM=dumb make -j $(nproc) --output-sync ci-test
+          # set SOURCE_DATE_EPOCH for reproducible PDFs
+          export SOURCE_DATE_EPOCH=0
+          TERM=dumb make -C LoopIntegrals -j $(nproc) --output-sync ci-test
+          cp ./LoopIntegrals/.codecov.yml ./
           curl -s https://codecov.io/bash | bash
+          git config --global user.name "Bot"
+          git config --global user.email "empty"
+          cd LoopIntegrals
+          CUR_SHA=$(git rev-parse --verify HEAD)
+          if [ "${{ matrix.image }}" = "gapsystem/gap-docker" ] && [ "$CUR_SHA" = "$(git rev-parse origin/master)" ] && [ $(dirname "$GITHUB_REPOSITORY") = "homalg-project" ]; then \
+            git worktree add gh-pages/ gh-pages || (echo "There was an error. Make sure there is a branch named 'gh-pages'. See https://github.com/homalg-project/PackageJanitor#error-there-was-an-error-make-sure-there-is-a-branch-named-gh-pages"; exit 1); \
+            git checkout master; \
+            ./make_dist.sh --token "${{ secrets.GITHUB_TOKEN }}"; \
+          else \
+            echo "Not making a release."; \
+          fi
